resolver: lts-13.5
packages:
- .
extra-deps:
- sandi-0.4.3
- git: https://github.com/aleshgo/encdec.git
  commit: 41eb87f27ea11e9444261672f9c077f057f2e089
- git: https://github.com/aleshgo/husk-prelude.git
  commit: 1cb39d2687a216e8a1cbe0e310ae08ab4cbfd104
